#string(APPEND CONFIG_ARGS " --enable-filesystem-hints=lustre")
#string(APPEND CPPDEFS " -DLINUX")
#if (DEBUG)
#  string(APPEND FFLAGS " -check all -ftrapuv")
#endif()
set(NETCDF_PATH "$ENV{NETCDF}")
#set(PIO_FILESYSTEM_HINTS "lustre")
#set(PNETCDF_PATH "$ENV{PNETCDFROOT}")
string(APPEND SLIBS " -L${NETCDF_PATH}/lib -lnetcdf -lnetcdff -lcurl -L$ENV{MKL_PATH}/lib/intel64 -lmkl_rt")
#string(APPEND SLIBS " -L$ENV{PIO_LIBDIR} -I$ENV{PIO_INCDIR} -lpioc -lpiof")

if (MPILIB STREQUAL mpich2)
  string(APPEND SLIBS " -mkl=cluster")
endif()
if (MPILIB STREQUAL mpi-serial)
  string(APPEND SLIBS " -mkl")
endif()
set(MPICC "mpicc")
set(MPICXX "mpicxx")
set(MPIFC "mpif90")
set(SCC "icc")
set(SCXX "icpc")
set(SFC "ifort")
set(SUPPORTS_CXX "TRUE")
 
